"""Conteúdo editorial. Texto factual, sem estatísticas inventadas. Revise com a equipe da agência."""

SCOPE_NOTE = (
    "O cuidador oferece apoio na rotina, companhia, higiene e conforto, alimentação, mobilidade segura e "
    "atenção ao bem-estar. Ele <strong>não é enfermeiro nem médico</strong>: não prescreve, não diagnostica e "
    "não realiza procedimentos de enfermagem (como injeções, curativos complexos ou sondas). Quando há necessidade "
    "clínica, a orientação é buscar profissional de saúde habilitado. Lembretes de medicação seguem sempre a prescrição "
    "médica e o que a família combinou."
)

# ---------------------------------------------------------------- SERVIÇOS
SERVICES = [
    dict(
        slug="cuidador-de-idosos", name="Cuidador de idosos",
        h1="Cuidador de idosos: acompanhamento profissional em casa",
        kw="cuidador de idosos", short="Rotina, companhia e segurança para o idoso em casa.",
        quick="Cuidador de idosos é o profissional que acompanha a pessoa idosa no dia a dia: ajuda na higiene, alimentação, "
              "locomoção, organização da rotina e companhia. O objetivo é manter conforto, segurança e autonomia possível, "
              "dando tranquilidade à família. A escolha do período e do perfil depende da necessidade de cada idoso.",
        problem="Sua família precisa de ajuda para cuidar de um idoso? Quando a rotina da casa não comporta o cuidado diário, "
                "é comum surgir culpa, cansaço e medo de quedas ou esquecimentos.",
        solution="Encontramos profissionais preparados para oferecer acompanhamento, companhia e suporte à rotina, de acordo com "
                 "a necessidade da família.",
        who=["Idosos que moram sozinhos e precisam de companhia e supervisão",
             "Idosos com dificuldade para higiene, alimentação ou locomoção",
             "Famílias que trabalham fora e não conseguem acompanhar o dia inteiro",
             "Cuidadores familiares sobrecarregados que precisam de apoio"],
        benefits=["Rotina organizada e previsível", "Mais segurança dentro de casa", "Companhia e estímulo no dia a dia",
                  "Família com mais tranquilidade e tempo de qualidade"],
        features=["Apoio no banho, vestuário e higiene pessoal", "Preparo e acompanhamento das refeições",
                  "Auxílio na locomoção e prevenção de quedas", "Estímulo a atividades leves e conversa",
                  "Lembretes de horários conforme prescrição médica", "Comunicação regular com a família"],
        faq=[("O cuidador de idosos pode dar banho?", "Sim. Apoio na higiene pessoal, incluindo o banho, faz parte da rotina do cuidador, respeitando a dignidade e o conforto do idoso."),
             ("Cuidador de idosos aplica injeção?", "Não. Procedimentos de enfermagem, como aplicar injeções, dependem de profissional de saúde habilitado."),
             ("Posso contratar apenas alguns dias por semana?", "Sim. É possível combinar dias e horários conforme a necessidade. Fale conosco para montar o plano ideal.")],
        related=["cuidador-domiciliar", "cuidador-noturno", "cuidador-24-horas"],
        blog=["o-que-faz-um-cuidador-de-idosos", "como-escolher-um-cuidador-de-idosos", "quando-contratar-um-cuidador"],
    ),
    dict(
        slug="cuidador-domiciliar", name="Cuidador domiciliar",
        h1="Cuidador domiciliar: cuidado humano dentro da sua casa",
        kw="cuidador domiciliar", short="Atendimento na casa do paciente, com rotina personalizada.",
        quick="Cuidador domiciliar é o profissional que presta cuidado e acompanhamento na casa da pessoa atendida. Ele apoia "
              "a rotina, a higiene, a alimentação e a mobilidade, mantendo a pessoa em um ambiente familiar. É indicado quando "
              "há necessidade de apoio contínuo ou em determinados períodos do dia.",
        problem="Permanecer em casa é o desejo de muitos idosos e pessoas em recuperação, mas a casa nem sempre está preparada nem há alguém disponível o tempo todo.",
        solution="O cuidador domiciliar leva apoio profissional ao ambiente que a pessoa conhece, respeitando hábitos, preferências e rotina da família.",
        who=["Pessoas que preferem se manter em casa com apoio", "Idosos com dependência parcial para atividades diárias",
             "Pessoas em recuperação que precisam de acompanhamento", "Famílias que moram longe e querem presença confiável"],
        benefits=["Conforto do ambiente familiar", "Atenção individualizada", "Rotina respeitada", "Flexibilidade de dias e horários"],
        features=["Avaliação inicial das necessidades", "Plano de rotina combinado com a família", "Apoio em higiene, alimentação e mobilidade",
                  "Atenção ao ambiente e riscos domésticos", "Registro e repasse das informações do dia"],
        faq=[("Como funciona o atendimento domiciliar?", "Conversamos com a família, entendemos a rotina e a necessidade, indicamos o profissional adequado e acompanhamos o início do atendimento."),
             ("O cuidador domiciliar faz limpeza da casa?", "O foco é o cuidado com a pessoa. Tarefas domésticas são combinadas previamente e limitadas ao que envolve diretamente o cuidado, como preparar a refeição."),
             ("Dá para trocar o profissional se necessário?", "Sim. Se o perfil não combinar, conversamos e buscamos outra indicação.")],
        related=["cuidador-de-idosos", "cuidador-24-horas", "cuidador-pos-operatorio"],
        blog=["como-preparar-a-casa-para-um-idoso", "como-organizar-a-rotina-de-um-idoso", "como-escolher-uma-agencia-de-cuidadores"],
    ),
    dict(
        slug="cuidador-24-horas", name="Cuidador 24 horas",
        h1="Cuidador 24 horas: presença contínua para quem precisa de apoio constante",
        kw="cuidador 24 horas", short="Cobertura contínua com escala de profissionais.",
        quick="Cuidador 24 horas é o atendimento contínuo, em que o cuidado não se interrompe de dia nem de noite. Em geral é "
              "organizado em escalas de profissionais, para respeitar descanso e jornada de trabalho. É indicado para pessoas com "
              "alta dependência ou que não podem ficar sozinhas em nenhum momento.",
        problem="Há situações em que ninguém da família consegue estar presente a qualquer hora, e a pessoa não pode ficar sem supervisão.",
        solution="Montamos uma escala com profissionais que se revezam, mantendo continuidade, comunicação e segurança.",
        who=["Pessoas com alta dependência funcional", "Idosos com demência em estágio que exige supervisão constante",
             "Pessoas acamadas ou com mobilidade muito reduzida", "Famílias sem rede de apoio para revezamento"],
        benefits=["Supervisão contínua", "Revezamento que evita cansaço do profissional", "Mais segurança nas madrugadas", "Passagem de plantão organizada"],
        features=["Escala planejada com a família", "Registro de intercorrências e rotina entre plantões", "Apoio em higiene, mobilização e alimentação",
                  "Atenção noturna ao conforto e à segurança", "Canal direto para ajustes"],
        faq=[("Um único cuidador faz 24 horas seguidas?", "Não é recomendado. O atendimento 24 horas costuma ser dividido em escalas com mais de um profissional, respeitando a legislação trabalhista e o descanso."),
             ("Qual a diferença entre cuidador 24h e noturno?", "O noturno cobre apenas a noite. O 24h cobre dia e noite, normalmente com revezamento."),
             ("Como é definido o valor?", "Depende de escala, perfil de cuidado e cidade. Solicite um orçamento pelo WhatsApp.")],
        related=["cuidador-noturno", "cuidador-para-pessoa-acamada", "cuidador-domiciliar"],
        blog=["como-funciona-um-cuidador-24-horas", "qual-a-jornada-de-trabalho-de-um-cuidador", "quanto-custa-um-cuidador-de-idosos"],
    ),
    dict(
        slug="cuidador-noturno", name="Cuidador noturno",
        h1="Cuidador noturno: segurança e descanso para toda a família",
        kw="cuidador noturno", short="Acompanhamento durante a noite e a madrugada.",
        quick="Cuidador noturno é o profissional que acompanha a pessoa durante a noite e a madrugada. Ele ajuda com idas ao banheiro, "
              "reposicionamento, desconforto e segurança. É indicado para quem acorda com frequência, tem risco de queda noturna ou "
              "quando a família precisa descansar.",
        problem="Noites mal dormidas, medo de uma queda no escuro e cansaço acumulado afetam quem cuida e quem é cuidado.",
        solution="Um profissional atento durante a noite garante assistência rápida e permite que a família recupere o sono.",
        who=["Idosos que acordam várias vezes à noite", "Pessoas com risco de queda ao levantar", "Pessoas com demência e agitação noturna",
             "Familiares exaustos por noites sem descanso"],
        benefits=["Atenção em todos os despertares", "Prevenção de quedas noturnas", "Família descansada", "Rotina de sono mais organizada"],
        features=["Acompanhamento a idas ao banheiro", "Reposicionamento no leito quando necessário", "Atenção a sinais de desconforto e comunicação à família",
                  "Ambiente calmo e iluminação segura", "Relato da noite pela manhã"],
        faq=[("Em que horário trabalha o cuidador noturno?", "Os horários são combinados com a família; muitos atendimentos ocorrem entre o fim da tarde e a manhã seguinte."),
             ("O cuidador noturno pode dormir?", "A rotina é combinada previamente. Para necessidades frequentes, a vigília é indicada; em outras situações, pode haver períodos de repouso sem perder a atenção."),
             ("Como contratar um cuidador noturno?", "Informe pelo WhatsApp a necessidade e os horários. Indicamos o profissional e combinamos o início.")],
        related=["cuidador-24-horas", "cuidador-de-idosos", "cuidador-para-alzheimer"],
        blog=["como-contratar-um-cuidador-para-o-periodo-noturno", "como-evitar-quedas-em-idosos", "como-funciona-um-cuidador-24-horas"],
    ),
    dict(
        slug="acompanhante-hospitalar", name="Acompanhante hospitalar",
        h1="Acompanhante hospitalar: companhia e apoio durante a internação",
        kw="acompanhante hospitalar", short="Presença e apoio na internação ou em consultas.",
        quick="Acompanhante hospitalar é o profissional que fica ao lado do paciente durante internação, exames ou consultas, oferecendo "
              "companhia, apoio na comunicação e conforto. Ele não substitui a equipe de saúde: auxilia no que é cuidado pessoal e "
              "avisa a equipe e a família quando necessário.",
        problem="Quando um familiar é internado, nem sempre alguém consegue permanecer no hospital, principalmente à noite.",
        solution="Um acompanhante preparado traz presença, acolhimento e comunicação com a família, respeitando as regras da instituição.",
        who=["Idosos internados que precisam de companhia", "Pacientes em exames ou consultas longas", "Famílias que trabalham e não podem revezar",
             "Pessoas com risco de confusão mental durante a internação"],
        benefits=["Presença constante", "Menos ansiedade para paciente e família", "Comunicação organizada", "Apoio em necessidades pessoais"],
        features=["Companhia e conforto", "Apoio na alimentação e higiene quando permitido pelo hospital", "Atenção à segurança do paciente",
                  "Aviso à equipe de enfermagem sobre necessidades", "Relato à família"],
        faq=[("Cuidador de idosos pode acompanhar no hospital?", "Sim, desde que a instituição permita acompanhante. Cada hospital tem regras próprias, que o profissional respeita."),
             ("O acompanhante realiza procedimentos de saúde?", "Não. Procedimentos são da equipe do hospital."),
             ("É possível contratar apenas para a noite?", "Sim, muitos acompanhamentos hospitalares são noturnos.")],
        related=["cuidador-pos-operatorio", "cuidador-24-horas", "cuidador-de-idosos"],
        blog=["cuidador-de-idosos-pode-acompanhar-no-hospital", "qual-a-diferenca-entre-cuidador-e-acompanhante", "quais-perguntas-fazer-antes-de-contratar-um-cuidador"],
    ),
    dict(
        slug="cuidador-pos-operatorio", name="Cuidador pós-operatório",
        h1="Cuidador para pós-operatório: apoio na recuperação em casa",
        kw="cuidador pós-operatório", short="Apoio seguro na volta para casa após cirurgia.",
        quick="Cuidador para pós-operatório apoia a pessoa em casa após uma cirurgia ou internação: ajuda na mobilidade, higiene, "
              "alimentação e conforto, seguindo as orientações da equipe médica. Ele não realiza procedimentos de enfermagem; "
              "reforça a rotina de recuperação definida pelos profissionais de saúde.",
        problem="A alta hospitalar traz alívio e insegurança: como se movimentar, tomar banho e seguir as orientações sem ajuda?",
        solution="Um cuidador ajuda a seguir a rotina orientada pela equipe médica, com segurança e acolhimento.",
        who=["Pessoas recém-operadas com restrição de movimento", "Idosos após cirurgia ortopédica ou outras", "Pessoas que moram sozinhas",
             "Famílias que não conseguem se ausentar do trabalho"],
        benefits=["Recuperação mais tranquila", "Apoio na mobilidade com segurança", "Rotina de repouso respeitada", "Menos risco de quedas"],
        features=["Auxílio para levantar, sentar e caminhar", "Apoio na higiene respeitando restrições", "Refeições conforme orientação",
                  "Lembretes de horários prescritos", "Aviso à família sobre qualquer alteração observada"],
        faq=[("O cuidador faz curativos?", "Curativos que exigem técnica são feitos por profissional de saúde habilitado. O cuidador apoia a rotina e avisa sobre alterações."),
             ("Por quanto tempo contratar?", "Depende da cirurgia e das orientações médicas. Muitas famílias começam por um período curto e ajustam."),
             ("Posso contratar por poucas horas por dia?", "Sim, é possível definir períodos específicos.")],
        related=["acompanhante-hospitalar", "cuidador-para-pessoa-com-mobilidade-reduzida", "cuidador-domiciliar"],
        blog=["quando-contratar-um-cuidador", "como-evitar-quedas-em-idosos", "como-preparar-a-casa-para-um-idoso"],
    ),
    dict(
        slug="cuidador-para-pessoa-acamada", name="Cuidador para pessoa acamada",
        h1="Cuidador para pessoa acamada: conforto, dignidade e atenção",
        kw="cuidador para pessoa acamada", short="Cuidado atento a quem permanece no leito.",
        quick="Cuidador para pessoa acamada acompanha quem passa a maior parte do tempo no leito, apoiando higiene, alimentação, "
              "reposicionamento e conforto, sempre conforme orientação da equipe de saúde. Atenção constante à dignidade e à comunicação "
              "com a família é parte central do atendimento.",
        problem="Cuidar de alguém acamado exige força, técnica e disponibilidade, e a sobrecarga é frequente na família.",
        solution="Profissionais com experiência em cuidado intensivo de rotina dividem essa responsabilidade com respeito e delicadeza.",
        who=["Pessoas com dependência total ou quase total", "Pessoas em recuperação prolongada", "Famílias que precisam de revezamento",
             "Quem já conta com equipe de saúde e precisa de apoio diário"],
        benefits=["Conforto e dignidade", "Rotina de higiene e posicionamento organizada", "Alívio para familiares", "Observação atenta de mudanças"],
        features=["Higiene no leito e troca de roupas", "Apoio na alimentação", "Mudança de posição conforme orientação", "Companhia e conversa",
                  "Comunicação com família e equipe de saúde"],
        faq=[("Cuidador pode fazer mudança de decúbito?", "Pode apoiar o reposicionamento conforme orientação da equipe de saúde da pessoa atendida."),
             ("Preciso de enfermeiro também?", "Quando há procedimentos de enfermagem, sim. O cuidador complementa a rotina."),
             ("Existe atendimento 24 horas?", "Sim, com escala de profissionais.")],
        related=["cuidador-24-horas", "cuidador-para-pessoa-com-mobilidade-reduzida", "cuidador-domiciliar"],
        blog=["como-funciona-um-cuidador-24-horas", "como-escolher-um-cuidador-de-idosos", "quanto-custa-um-cuidador-de-idosos"],
    ),
    dict(
        slug="cuidador-para-alzheimer", name="Cuidador para Alzheimer",
        h1="Cuidador para Alzheimer: paciência, rotina e acolhimento",
        kw="cuidador para Alzheimer", short="Rotina estável e atenção à segurança de quem tem demência.",
        quick="Cuidador para Alzheimer acompanha pessoas com a doença oferecendo rotina estável, segurança, companhia e comunicação "
              "paciente. Ele ajuda nas atividades diárias, reduz riscos como saídas desorientadas e quedas, e comunica a família sobre mudanças "
              "de comportamento, sem substituir o acompanhamento médico.",
        problem="A doença de Alzheimer altera memória e comportamento, e a família pode se sentir despreparada para lidar com confusão, agitação e dependência crescente.",
        solution="Profissionais orientados a lidar com demência trabalham com rotina, calma e segurança, apoiando também quem convive com o idoso.",
        who=["Pessoas com diagnóstico de Alzheimer ou outras demências", "Idosos com esquecimentos que exigem supervisão", "Famílias que precisam de apoio e orientação",
             "Pessoas com alteração de sono ou agitação no fim do dia"],
        benefits=["Rotina previsível", "Ambiente mais seguro", "Menos estresse para a família", "Estímulo respeitoso e companhia"],
        features=["Rotina estruturada e repetitiva", "Atenção a risco de fuga e quedas", "Comunicação simples e calma",
                  "Apoio em higiene e alimentação", "Estímulo com músicas, fotos e atividades leves", "Relato de mudanças ao responsável"],
        faq=[("O cuidador precisa ter experiência com Alzheimer?", "Indicamos profissionais com perfil e experiência compatíveis com demência, conforme o estágio da pessoa."),
             ("O cuidador administra medicamentos?", "Pode lembrar horários conforme a prescrição médica e as orientações da família; decisões sobre medicação são do médico."),
             ("Atende à noite?", "Sim. Muitos casos exigem presença noturna.")],
        related=["cuidador-noturno", "cuidador-24-horas", "cuidador-de-idosos"],
        blog=["cuidados-com-idosos-com-alzheimer", "como-organizar-a-rotina-de-um-idoso", "como-preparar-a-casa-para-um-idoso"],
    ),
    dict(
        slug="cuidador-para-parkinson", name="Cuidador para Parkinson",
        h1="Cuidador para Parkinson: apoio à mobilidade e à autonomia",
        kw="cuidador para Parkinson", short="Segurança na locomoção e paciência com o ritmo da pessoa.",
        quick="Cuidador para Parkinson apoia pessoas com a doença na mobilidade, higiene, alimentação e rotina, respeitando o ritmo "
              "e estimulando a autonomia possível. Atenção a quedas, tremores e rigidez é parte do trabalho, sempre seguindo as orientações "
              "da equipe de saúde que acompanha a pessoa.",
        problem="Rigidez, lentidão e risco de queda tornam tarefas simples mais difíceis, e a pressa do dia a dia pode aumentar a frustração.",
        solution="Um cuidador paciente e atento oferece apoio sem tirar a autonomia que a pessoa ainda tem.",
        who=["Pessoas com doença de Parkinson em diferentes estágios", "Pessoas com risco de queda e dificuldade de marcha", "Famílias que precisam de suporte na rotina",
             "Quem faz fisioterapia e precisa de apoio para dar continuidade"],
        benefits=["Mais segurança ao caminhar", "Respeito ao tempo da pessoa", "Rotina organizada em torno de horários importantes", "Apoio à autonomia"],
        features=["Acompanhamento na locomoção e transferências", "Apoio em refeições e deglutição conforme orientação", "Lembretes de horários prescritos",
                  "Estímulo aos exercícios indicados pela equipe de saúde", "Ambiente organizado para reduzir riscos"],
        faq=[("O cuidador ajuda nos exercícios?", "Pode estimular e acompanhar exercícios orientados por fisioterapeuta ou médico, sem prescrevê-los."),
             ("Existe cuidador só para a hora das refeições?", "Sim, é possível contratar períodos específicos."),
             ("O cuidador lida com tremores?", "Ele apoia com paciência e segurança; questões clínicas são tratadas pela equipe de saúde.")],
        related=["cuidador-para-pessoa-com-mobilidade-reduzida", "cuidador-de-idosos", "cuidador-domiciliar"],
        blog=["cuidados-para-idosos-com-parkinson", "como-evitar-quedas-em-idosos", "como-preparar-a-casa-para-um-idoso"],
    ),
    dict(
        slug="cuidador-para-pessoa-com-mobilidade-reduzida", name="Cuidador para mobilidade reduzida",
        h1="Cuidador para pessoa com mobilidade reduzida: locomoção com segurança",
        kw="cuidador para pessoa com mobilidade reduzida", short="Apoio para andar, transferir-se e manter a rotina.",
        quick="Cuidador para pessoa com mobilidade reduzida ajuda na locomoção dentro e fora de casa, nas transferências (cama, cadeira, banheiro) "
              "e nas atividades diárias. O foco é prevenir quedas e manter a independência possível, com técnicas seguras e atenção ao ambiente.",
        problem="Quando andar ou se levantar fica difícil, tarefas básicas viram risco e a pessoa pode deixar de sair de casa.",
        solution="O cuidador oferece apoio físico seguro e incentiva a pessoa a manter sua rotina e a convivência social.",
        who=["Pessoas que usam bengala, andador ou cadeira de rodas", "Idosos com fragilidade ou histórico de quedas", "Pessoas em reabilitação",
             "Pessoas que precisam de companhia para consultas e passeios"],
        benefits=["Menos risco de queda", "Mais autonomia e circulação", "Acompanhamento em saídas", "Ambiente adaptado"],
        features=["Apoio em transferências e caminhadas", "Acompanhamento em consultas e passeios", "Observação de riscos no ambiente",
                  "Apoio em higiene e vestuário", "Estímulo à atividade conforme orientação"],
        faq=[("O cuidador acompanha em consultas?", "Sim, pode acompanhar e apoiar na locomoção e no retorno para casa."),
             ("Ele ajuda com cadeira de rodas?", "Sim, apoia transferências e deslocamentos com segurança."),
             ("Preciso adaptar a casa?", "Pequenas adaptações ajudam muito. Veja nosso guia de preparação da casa.")],
        related=["cuidador-para-pessoa-acamada", "cuidador-para-parkinson", "cuidador-pos-operatorio"],
        blog=["como-evitar-quedas-em-idosos", "como-preparar-a-casa-para-um-idoso", "quando-contratar-um-cuidador"],
    ),
]

# ---------------------------------------------------------------- ARTIGOS
ARTICLES = [
    dict(slug="como-escolher-um-cuidador-de-idosos", title="Como escolher um cuidador de idosos?", cluster="Contratação",
         quick="Para escolher um cuidador de idosos, defina a necessidade (período, tipo de apoio), peça referências, converse sobre experiência, "
               "avalie a empatia entre profissional e idoso e combine regras e valores por escrito. Contratar por uma agência facilita a seleção e a substituição.",
         sections=[("Defina primeiro o que o idoso precisa", "<p>Liste as atividades em que há dificuldade: higiene, alimentação, locomoção, companhia, medicação. Anote também horários críticos, como noites e finais de semana.</p>"),
                   ("Critérios para avaliar o profissional", "<ul><li>Experiência com o perfil do idoso (demência, mobilidade reduzida etc.)</li><li>Referências verificáveis</li><li>Postura calma, respeitosa e comunicativa</li><li>Disponibilidade para o período combinado</li></ul>"),
                   ("Faça um período de adaptação", "<p>Os primeiros dias mostram se há afinidade. Observe a reação do idoso e combine um retorno com a família.</p>")],
         services=["cuidador-de-idosos"], faq=[("Entrevistar o cuidador é importante?", "Sim. A conversa mostra postura, experiência e se o perfil combina com o idoso.")]),
    dict(slug="quanto-custa-um-cuidador-de-idosos", title="Quanto custa um cuidador de idosos?", cluster="Contratação",
         quick="O custo de um cuidador de idosos varia conforme período (diurno, noturno, 24 horas), complexidade do cuidado, experiência do profissional, "
               "cidade e forma de contratação. Não existe valor único: o caminho confiável é solicitar um orçamento informando a necessidade da família.",
         sections=[("O que influencia o valor", "<ul><li><strong>Carga horária:</strong> poucas horas, turno diurno, noturno ou 24h</li><li><strong>Complexidade:</strong> demência, pessoa acamada, mobilidade reduzida</li><li><strong>Regime:</strong> escala, número de profissionais e dias da semana</li><li><strong>Forma de contratação:</strong> agência ou contratação direta, com encargos e responsabilidades diferentes</li></ul>"),
                   ("Agência ou contratação direta?", "<p>Na contratação direta a família assume a responsabilidade trabalhista e a reposição em faltas. Na agência, esses pontos são tratados no contrato do serviço. Compare sempre o que está incluído.</p>"),
                   ("Como pedir um orçamento", "<p>Informe a cidade, o período desejado e a situação do idoso. Com isso é possível indicar o profissional e o valor.</p>")],
         services=["cuidador-de-idosos", "cuidador-24-horas", "cuidador-noturno"], faq=[("Existe valor fixo por hora?", "Não de forma universal. Varia com a necessidade e a região; por isso o orçamento é personalizado.")]),
    dict(slug="o-que-faz-um-cuidador-de-idosos", title="O que faz um cuidador de idosos?", cluster="Fundamentos",
         quick="Um cuidador de idosos é o profissional que apoia a pessoa idosa nas atividades diárias: higiene, alimentação, locomoção, organização da rotina e companhia. "
               "Ele não substitui médicos ou enfermeiros e não realiza procedimentos de saúde que exigem formação específica.",
         sections=[("Atividades do cuidador", "<ul><li>Apoio no banho, vestuário e cuidados pessoais</li><li>Preparo e acompanhamento das refeições</li><li>Ajuda na locomoção e prevenção de quedas</li><li>Companhia, conversa e estímulo</li><li>Lembretes de horários prescritos</li></ul>"),
                   ("O que não faz parte da função", "<p>Aplicar injeções, realizar curativos complexos, prescrever ou alterar medicamentos e diagnosticar são atividades de profissionais de saúde habilitados.</p>")],
         services=["cuidador-de-idosos", "cuidador-domiciliar"], faq=[("Cuidador e enfermeiro são a mesma coisa?", "Não. O enfermeiro tem formação em saúde e executa procedimentos técnicos. O cuidador apoia o dia a dia.")]),
    dict(slug="qual-a-diferenca-entre-cuidador-e-acompanhante", title="Qual a diferença entre cuidador e acompanhante?", cluster="Fundamentos",
         quick="O acompanhante oferece principalmente companhia e presença, como em consultas ou internações. O cuidador também presta apoio nas atividades diárias, como higiene, alimentação e locomoção. "
               "Na prática os termos se misturam, por isso vale detalhar as tarefas desejadas ao contratar.",
         sections=[("Comparativo rápido", "<table><thead><tr><th>Aspecto</th><th>Acompanhante</th><th>Cuidador</th></tr></thead><tbody><tr><td>Foco</td><td>Companhia e presença</td><td>Cuidado pessoal e rotina</td></tr><tr><td>Higiene e banho</td><td>Em geral não</td><td>Sim</td></tr><tr><td>Local comum</td><td>Hospital, consultas</td><td>Casa</td></tr></tbody></table>"),
                   ("Como decidir", "<p>Se a pessoa é independente e precisa de companhia, o acompanhante basta. Se há dificuldade em atividades diárias, o cuidador é mais indicado.</p>")],
         services=["acompanhante-hospitalar", "cuidador-de-idosos"]),
    dict(slug="quando-contratar-um-cuidador", title="Quando contratar um cuidador?", cluster="Contratação",
         quick="Contrate um cuidador quando o idoso ou a pessoa em recuperação precisar de ajuda frequente na rotina, houver risco de quedas, esquecimentos importantes, "
               "sobrecarga da família ou alta hospitalar sem rede de apoio. Quanto antes a necessidade é percebida, mais fácil é organizar a transição.",
         sections=[("Sinais de que é hora de buscar ajuda", "<ul><li>Dificuldade com banho, alimentação ou locomoção</li><li>Quedas ou quase quedas</li><li>Esquecimentos que colocam em risco (fogão ligado, medicamentos)</li><li>Isolamento e tristeza</li><li>Familiar cuidador exausto</li></ul>"),
                   ("Situações em que o cuidador pode ajudar", "<p>Após cirurgia, em rotinas de demência, quando o idoso mora sozinho ou quando a família trabalha o dia todo.</p>")],
         services=["cuidador-de-idosos", "cuidador-pos-operatorio"]),
    dict(slug="cuidador-de-idosos-pode-acompanhar-no-hospital", title="Cuidador de idosos pode acompanhar no hospital?", cluster="Hospital",
         quick="Sim, o cuidador pode acompanhar o idoso no hospital, desde que a instituição permita acompanhante e siga suas regras. Ele oferece companhia, apoio na higiene e na alimentação quando autorizado, e avisa a equipe e a família. Procedimentos clínicos continuam sendo da equipe de saúde.",
         sections=[("O que o acompanhante faz no hospital", "<p>Fica ao lado do paciente, ajuda em necessidades pessoais, comunica desconfortos à enfermagem e traz segurança emocional.</p>"),
                   ("Antes de contratar", "<p>Consulte o hospital sobre regras de acompanhante, horários e identificação. Informe isso ao contratar o serviço.</p>")],
         services=["acompanhante-hospitalar"]),
    dict(slug="como-funciona-um-cuidador-24-horas", title="Como funciona um cuidador 24 horas?", cluster="Rotina e jornada",
         quick="O cuidador 24 horas funciona em escalas, com mais de um profissional se revezando para manter a presença contínua. Isso garante descanso adequado e continuidade do cuidado, com passagem de plantão e registro das informações do dia.",
         sections=[("Comparativo de formatos", "<table><thead><tr><th>Serviço</th><th>Indicação</th><th>Período</th></tr></thead><tbody><tr><td>Cuidador diário</td><td>Rotina</td><td>Dia</td></tr><tr><td>Cuidador noturno</td><td>Acompanhamento</td><td>Noite</td></tr><tr><td>Cuidador 24h</td><td>Necessidade contínua</td><td>24h</td></tr></tbody></table>"),
                   ("Como as escalas são organizadas", "<p>Escalas comuns dividem o dia e a noite entre profissionais, com folgas programadas. A definição depende da legislação aplicável e do acordo com a família.</p>")],
         services=["cuidador-24-horas", "cuidador-noturno"]),
    dict(slug="qual-a-jornada-de-trabalho-de-um-cuidador", title="Qual a jornada de trabalho de um cuidador?", cluster="Rotina e jornada",
         quick="A jornada do cuidador depende do tipo de vínculo e do formato do atendimento: períodos diurnos, noturnos ou escalas. Descanso, folgas e limites de horário precisam ser respeitados e combinados formalmente. Consulte a legislação trabalhista e um profissional jurídico para a situação específica.",
         sections=[("Formatos mais comuns", "<ul><li>Diurno (por exemplo, algumas horas ou turno)</li><li>Noturno</li><li>Escalas com revezamento para 24 horas</li></ul>"),
                   ("Atenção a aspectos legais", "<p>Regras sobre jornada, descanso e vínculo variam conforme a modalidade de contratação. Em caso de dúvida, busque orientação jurídica ou contábil.</p>")],
         services=["cuidador-24-horas", "cuidador-noturno"]),
    dict(slug="como-contratar-um-cuidador-para-o-periodo-noturno", title="Como contratar um cuidador para o período noturno?", cluster="Contratação",
         quick="Para contratar um cuidador noturno, informe horários, as necessidades da noite (idas ao banheiro, risco de queda, agitação) e a cidade. A agência indica o profissional, combina início e acompanha a adaptação nos primeiros dias.",
         sections=[("Passo a passo em 5 etapas", "<ol><li>Descreva a rotina noturna do idoso</li><li>Defina horários e dias</li><li>Solicite o orçamento</li><li>Conheça o profissional indicado</li><li>Inicie com período de adaptação</li></ol>"),
                   ("O que combinar", "<p>Regras da casa, quem avisar em caso de intercorrência e se haverá períodos de repouso.</p>")],
         services=["cuidador-noturno"]),
    dict(slug="cuidados-com-idosos-com-alzheimer", title="Cuidados com idosos com Alzheimer", cluster="Condições de saúde",
         quick="Cuidar de quem tem Alzheimer exige rotina estável, ambiente seguro, comunicação calma e paciência. Mantenha horários regulares, reduza riscos na casa, simplifique escolhas e acompanhe com a equipe médica. Apoio profissional ajuda a família a lidar com a evolução da doença.",
         sections=[("Boas práticas no dia a dia", "<ul><li>Manter horários de refeição, banho e sono</li><li>Falar frases curtas e olhar nos olhos</li><li>Evitar discussões e correções bruscas</li><li>Remover riscos (tapetes soltos, produtos de limpeza acessíveis)</li></ul>"),
                   ("Quando buscar apoio", "<p>Agitação ao entardecer, saídas desorientadas e dificuldades com higiene indicam necessidade de mais suporte. A orientação médica continua essencial.</p>")],
         services=["cuidador-para-alzheimer"]),
    dict(slug="cuidados-para-idosos-com-parkinson", title="Cuidados para idosos com Parkinson", cluster="Condições de saúde",
         quick="Idosos com Parkinson se beneficiam de ambiente seguro, rotina organizada, apoio na locomoção e respeito ao ritmo. Siga os horários de tratamento definidos pelo médico, estimule atividades orientadas por profissionais de saúde e previna quedas.",
         sections=[("Segurança e mobilidade", "<p>Ambientes sem obstáculos, bom contraste, barras de apoio e calçados firmes ajudam. O cuidador acompanha a marcha e as transferências.</p>"),
                   ("Rotina e autonomia", "<p>Dar tempo para a pessoa executar tarefas e adaptar objetos do dia a dia preserva a autonomia.</p>")],
         services=["cuidador-para-parkinson"]),
    dict(slug="como-preparar-a-casa-para-um-idoso", title="Como preparar a casa para um idoso", cluster="Segurança",
         quick="Preparar a casa para um idoso significa reduzir riscos de queda e facilitar a rotina: iluminação adequada, piso antiderrapante no banheiro, barras de apoio, retirada de tapetes soltos, objetos de uso diário ao alcance e caminhos livres.",
         sections=[("Checklist por ambiente", "<ul><li><strong>Banheiro:</strong> piso antiderrapante, barras, assento de banho</li><li><strong>Quarto:</strong> luz de apoio noturna, cama em altura adequada</li><li><strong>Sala e corredores:</strong> sem fios e tapetes soltos</li><li><strong>Cozinha:</strong> itens frequentes ao alcance</li></ul>"),
                   ("Quando pedir ajuda profissional", "<p>Terapeuta ocupacional ou profissional de reforma podem orientar adaptações específicas.</p>")],
         services=["cuidador-domiciliar", "cuidador-para-pessoa-com-mobilidade-reduzida"]),
    dict(slug="como-evitar-quedas-em-idosos", title="Como evitar quedas em idosos", cluster="Segurança",
         quick="Para evitar quedas em idosos: mantenha o ambiente iluminado e livre de obstáculos, use calçados firmes, instale barras de apoio, incentive atividade física orientada, revise medicamentos com o médico e conte com acompanhamento em momentos de maior risco, como banho e noite.",
         sections=[("Principais cuidados", "<ul><li>Iluminação em corredores e banheiro</li><li>Retirar tapetes soltos</li><li>Calçado fechado e antiderrapante</li><li>Levantar devagar da cama</li></ul>"),
                   ("Quando contar com um cuidador", "<p>Momentos de risco, como banho e idas ao banheiro à noite, ficam mais seguros com acompanhamento.</p>")],
         services=["cuidador-noturno", "cuidador-para-pessoa-com-mobilidade-reduzida"]),
    dict(slug="como-organizar-a-rotina-de-um-idoso", title="Como organizar a rotina de um idoso", cluster="Rotina e jornada",
         quick="Organize a rotina do idoso com horários regulares de acordar, refeições, medicação prescrita, atividades leves, descanso e sono. Previsibilidade traz segurança, melhora o humor e facilita o trabalho de quem cuida.",
         sections=[("Modelo simples de rotina", "<ol><li>Manhã: higiene, café, atividade leve</li><li>Meio do dia: almoço e descanso</li><li>Tarde: convivência, caminhada, lazer</li><li>Noite: jantar leve e preparo para dormir</li></ol>"),
                   ("Adapte ao idoso", "<p>Preferências e hábitos antigos devem ser mantidos sempre que possível.</p>")],
         services=["cuidador-de-idosos", "cuidador-domiciliar"]),
    dict(slug="como-escolher-uma-agencia-de-cuidadores", title="Como escolher uma agência de cuidadores?", cluster="Contratação",
         quick="Ao escolher uma agência de cuidadores, avalie processo de seleção, transparência de contrato e valores, reposição de profissionais, atendimento à família, área de cobertura, canais de contato e referências reais. Desconfie de promessas exageradas e de falta de informações institucionais.",
         sections=[("Critérios objetivos", "<ul><li>Processo de seleção e verificação de profissionais</li><li>Contrato claro e valores transparentes</li><li>Reposição quando houver falta</li><li>Suporte à família após o início</li><li>Dados da empresa verificáveis (CNPJ, endereço, contatos)</li></ul>"),
                   ("Veja também", "<p>Consulte nossa página <a href=\"/qual-agencia-contratar/\">Qual agência devo contratar?</a> com um checklist completo.</p>")],
         services=["cuidador-domiciliar"]),
    dict(slug="quais-perguntas-fazer-antes-de-contratar-um-cuidador", title="Quais perguntas fazer antes de contratar um cuidador?", cluster="Contratação",
         quick="Antes de contratar, pergunte sobre experiência com o perfil do idoso, referências, disponibilidade, atividades que realiza e as que não realiza, como lida com emergências, regras de substituição e forma de pagamento. As respostas mostram preparo e transparência.",
         sections=[("Perguntas essenciais", "<ul><li>Que experiência você tem com idosos nessa situação?</li><li>O que você faz em caso de queda ou mal-estar?</li><li>Quais atividades não faz?</li><li>Como é feita a substituição em faltas?</li><li>Como serão repassadas as informações do dia?</li></ul>"),
                   ("Combine por escrito", "<p>Horários, tarefas e valores devem constar em contrato.</p>")],
         services=["cuidador-de-idosos", "acompanhante-hospitalar"]),
]

# ---------------------------------------------------------------- CIDADES
CITIES = [
    dict(slug="fortaleza", name="Fortaleza",
         intro="Em Fortaleza, capital do Ceará, a demanda por cuidadores de idosos é marcada por grandes distâncias entre bairros, trânsito intenso e famílias que dependem do atendimento em casa para manter a rotina.",
         quick="Atendemos Fortaleza com cuidadores de idosos para períodos diurnos, noturnos e 24 horas, incluindo acompanhamento hospitalar e pós-operatório. Informe o bairro e a necessidade pelo WhatsApp para receber a indicação do profissional.",
         local=[("Bairros e regiões", "Atendimento em bairros como Aldeota, Meireles, Cocó, Benfica, Messejana e demais regiões da cidade, conforme disponibilidade de profissionais. Confirme a cobertura do seu bairro conosco."),
                ("Deslocamento e trânsito", "Distâncias e horários de pico influenciam a chegada e a troca de plantões. Planejamos escalas considerando o trajeto do profissional para reduzir atrasos."),
                ("Clima quente", "O calor do litoral cearense exige atenção à hidratação, à ventilação do ambiente e à roupa adequada, pontos que o cuidador observa na rotina do idoso."),
                ("Hospitais e consultas", "Muitas famílias precisam de acompanhante para consultas, exames e internações em hospitais da capital. Ajustamos o serviço às regras de cada instituição.")],
         faq=[("Vocês atendem em todos os bairros de Fortaleza?", "Buscamos atender a cidade toda; a cobertura por bairro é confirmada no primeiro contato."),
              ("Há cuidador noturno em Fortaleza?", "Sim, indicamos profissionais para o período noturno e para escalas de 24 horas.")]),
    dict(slug="caucaia", name="Caucaia",
         intro="Caucaia integra a Região Metropolitana de Fortaleza e reúne áreas urbanas e litorâneas, como Iparana e Tabapuá, onde muitas famílias buscam apoio domiciliar para idosos.",
         quick="Atendemos Caucaia com cuidadores de idosos em turnos diurnos, noturnos e escalas de 24 horas. Informe seu bairro e a necessidade pelo WhatsApp para verificarmos disponibilidade na sua região.",
         local=[("Regiões atendidas", "Centro de Caucaia e áreas como Iparana, Tabapuá e arredores, conforme disponibilidade. Confirmamos a cobertura no primeiro contato."),
                ("Deslocamento até Fortaleza", "Muitas famílias têm consultas e exames em Fortaleza. Podemos organizar acompanhamento no deslocamento e na consulta."),
                ("Rotina em área litorânea", "Calor e umidade pedem atenção à hidratação e ao conforto do ambiente.")],
         faq=[("Vocês atendem na praia de Iparana?", "Atendemos domicílios em Caucaia conforme disponibilidade; confirme o endereço pelo WhatsApp."),
              ("É possível contratar apenas para acompanhar consultas em Fortaleza?", "Sim, é possível definir períodos específicos.")]),
    dict(slug="eusebio", name="Eusébio",
         intro="Eusébio, vizinho a Fortaleza, tem crescimento residencial acelerado e muitas famílias que precisam de cuidado domiciliar para idosos com rotina organizada e segurança.",
         quick="Atendemos Eusébio com cuidadores de idosos para períodos diurnos, noturnos e 24 horas, além de acompanhamento em consultas. Informe o endereço e a necessidade pelo WhatsApp para receber a indicação.",
         local=[("Regiões atendidas", "Centro de Eusébio e bairros residenciais próximos, conforme disponibilidade. A cobertura exata é confirmada no contato."),
                ("Condomínios", "Atendemos residências e condomínios, respeitando as regras de acesso de cada local."),
                ("Proximidade com Fortaleza", "A proximidade facilita acompanhar consultas e exames na capital quando necessário.")],
         faq=[("Vocês atendem em condomínios de Eusébio?", "Sim, respeitando regras de acesso e portaria do condomínio."),
              ("Há atendimento 24 horas em Eusébio?", "Sim, com escala de profissionais.")]),
    dict(slug="aquiraz", name="Aquiraz",
         intro="Aquiraz combina centro histórico, áreas residenciais e regiões litorâneas como Porto das Dunas e Prainha, com famílias que precisam de cuidado domiciliar para idosos.",
         quick="Atendemos Aquiraz com cuidadores de idosos em turnos diurnos, noturnos e escalas de 24 horas. Informe seu endereço e a necessidade pelo WhatsApp para verificarmos a disponibilidade na região.",
         local=[("Regiões atendidas", "Centro de Aquiraz e áreas como Porto das Dunas e Prainha, conforme disponibilidade. Confirmamos a cobertura no primeiro contato."),
                ("Segunda residência e moradores sazonais", "Há casas de uso sazonal. Podemos organizar atendimento em períodos específicos."),
                ("Distância de Fortaleza", "Para consultas na capital, organizamos acompanhamento no trajeto e na consulta.")],
         faq=[("Vocês atendem em Porto das Dunas?", "Atendemos domicílios em Aquiraz conforme disponibilidade; confirme o endereço pelo WhatsApp."),
              ("Dá para contratar só por temporada?", "Sim, definimos períodos conforme a necessidade.")]),
]

# ---------------------------------------------------------------- FAQ GLOBAL
GLOBAL_FAQ = [
    ("Vocês atendem idosos em casa?", "Sim. O atendimento é domiciliar, na casa da família, com profissionais selecionados conforme a necessidade."),
    ("Vocês trabalham com cuidadores noturnos?", "Sim. Indicamos cuidadores para a noite e para escalas de 24 horas."),
    ("É possível contratar por períodos específicos?", "Sim. É possível definir dias, horários e duração, de poucas horas a escalas contínuas."),
    ("Como funciona a seleção dos profissionais?", "Reunimos informações da necessidade da família e indicamos profissionais com perfil e experiência compatíveis, com entrevista, verificação de referências e acompanhamento no início."),
    ("Como solicito um cuidador?", "Pelo WhatsApp ou pelo formulário do site. Informe cidade, tipo de cuidado e período desejado."),
    ("Quais cidades são atendidas?", "Fortaleza, Caucaia, Eusébio e Aquiraz. Consulte a página de áreas atendidas para outras regiões."),
    ("Quanto custa o serviço?", "O valor depende do período, da complexidade e da cidade. Solicite um orçamento pelo WhatsApp."),
    ("O cuidador pode administrar medicamentos?", "O cuidador pode lembrar horários conforme a prescrição médica. Prescrever, alterar doses ou aplicar injeções são atividades de profissionais de saúde habilitados."),
]
